FROM oracle/graalvm-ce:20.3.0-java11 AS builder

RUN gu install native-image

RUN curl --location --output /usr/local/bin/aws-lambda-rie \
        https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod a+x /usr/local/bin/aws-lambda-rie

COPY target/uberjar/hello-world.jar /

RUN native-image \
        --no-fallback \
        --report-unsupported-elements-at-runtime \
        --initialize-at-build-time \
        -H:+PrintAnalysisCallTree \
        -jar hello-world.jar hello-world && \
    chmod a+x hello-world

########################################

FROM ubuntu

COPY --from=builder /usr/local/bin/aws-lambda-rie /usr/local/bin/aws-lambda-rie

COPY lambda-bootstrap.sh /
COPY --from=builder /hello-world /

CMD ["/lambda-bootstrap.sh", "/hello-world"]
