FROM amazoncorretto:11

RUN curl --location --output /usr/local/bin/aws-lambda-rie \
        https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod a+x /usr/local/bin/aws-lambda-rie

COPY lambda-bootstrap.sh /lambda-bootstrap.sh
COPY target/uberjar/emergency-letter.jar emergency-letter.jar

# com.amazonaws.services.lambda.runtime.api.client.util.EnvWriter.<init> accesses java.util.Collections$UnmodifiableMap.m
CMD ["/lambda-bootstrap.sh", "/usr/bin/java", \
        "--illegal-access=deny", \
        "--add-opens", "java.base/java.util=ALL-UNNAMED", \
        "-XX:MaxRAMPercentage=75.0", "-XX:+ExitOnOutOfMemoryError", \
        "-XshowSettings:vm", "-XX:+PrintCommandLineFlags", \
        "-jar", "emergency-letter.jar"]
